name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create directories for artifacts
      run: |
        mkdir -p build-scans/3-build-scan-build-macos-12-jdk-21/spool
        mkdir -p build-scans/3-build-scan-build-windows-latest-jdk-21/spool

    - name: Create sample files
      run: |
        echo "Sample content for macos scan" > build-scans/3-build-scan-build-macos-12-jdk-21/spool/38c1fc8e-2885-4b39-81a9-567d8a3543fe.scan
        echo "Sample content for windows scan" > build-scans/3-build-scan-build-windows-latest-jdk-21/spool/439cec07-d102-4b3a-9b22-1e112b652b14.scan

    - name: Upload renamed scan files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-scan
        path: build-scans/**
