name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Rename scan.scan and scan.properties files
      run: |
        mv scan.scan anupamas01_scan.scan
        mv scan.properties anupamas01_scan.properties

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload scan files to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: scan-files
        path: |
          anupamas01_scan.scan
          anupamas01_scan.properties
